platform :ios, '7.0'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'AFNetworking', '~> 2.3.1'
pod 'Masonry', '~> 0.6.1'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
source 'https://github.com/CocoaPods/Specs.git'
